# Generated by Django 4.1.3 on 2022-11-04 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="customerrole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Group_Name", models.CharField(max_length=100)),
                ("Group_Level", models.IntegerField()),
                ("Status", models.CharField(max_length=8)),
            ],
        ),
    ]
