# Generated by Django 4.1.3 on 2022-11-08 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecomapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="managecustomer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Group_Name", models.CharField(max_length=100)),
                ("Group_Level", models.IntegerField()),
                (
                    "Status",
                    models.CharField(
                        choices=[("Active", "Active"), ("Deactive", "Deactive")],
                        max_length=8,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="customerrole",
            name="Image",
            field=models.ImageField(blank=True, null=True, upload_to="myimage"),
        ),
        migrations.AlterField(
            model_name="customerrole",
            name="Status",
            field=models.CharField(
                choices=[("Active", "Active"), ("Deactive", "Deactive")], max_length=8
            ),
        ),
    ]
